import fetch from 'node-fetch'
// learn here: https://www.npmjs.com/package/node-fetch#simple-post

// const res = fetch('https://loveapi.ml/fso/patients.json').then((res) =>
// 	res.json()
// )

// const text = res.then((t) => console.log(t))

const fresh_token_url = 'http://localhost:4000/fresh-tokens'

const rt =
	'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImppbSIsImlhdCI6MTYxOTQyODYyOCwiZXhwIjoxNjIwMDMzNDI4fQ.CkeM0Zybu0jn2lEpg0lSX8udQ2mF3_H8AORyiaA3eyE'

fetch(fresh_token_url, {
	method: 'POST',
	headers: {
		'Content-Type': 'application/json',
		Authorization: `Bearer ${rt}`,
	},
	// body: JSON.stringify(data), // body data type must match "Content-Type" header
})
	.then((res) => {
		console.log('Got status code', res.status)
		if (res.status >= 200 && res.status <= 300) {
			return res.json()
		} else {
			return res.text() // Getting the message generated by the server.
		}
	})
	.then((jsonOrText) => console.log(jsonOrText))
	.catch((e) => {
		console.log('shit..., error thrown from backend.')
		// console.log(e)
	})
