curl 'http://localhost:6001/subscribe' \
  -H 'Accept: */*' \
  -H 'Accept-Language: en,hi;q=0.9,fi;q=0.8' \
  -H 'Connection: keep-alive' \
  -H 'Origin: http://localhost:6001' \
  -H 'Referer: http://localhost:6001/' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Site: same-origin' \
  -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.88 Safari/537.36' \
  -H 'content-type: application/json' \
  -H 'sec-ch-ua: " Not A;Brand";v="99", "Chromium";v="100", "Google Chrome";v="100"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "Linux"' \
  --data-raw '{"endpoint":"https://fcm.googleapis.com/fcm/send/dotnldXWqrk:APA91bGzN4T6VjR3VxfTg6mI9XoAiqszwFhWumJ4HdrR8Bw7Ol77TqsZucy1hTv9qIDMEMKIiXIZNE8offwgTg_APPpWQctRPg0OmOmQpVDvGJOgQzzZx-MzBHUbZE1tgm5YIMl5aVTx","expirationTime":null,"keys":{"p256dh":"BP0YVfYzk9LGhj15hpoR1T9J7Q0eVnNfN3RBUxoXu7DrEANJHBjIrWJXpN5Sf8bzr0lXuWSatPKEWAXnxXy0JRI","auth":"_dVtFQVkQomkKNktJUxpVw"}}' \
  --compressed
